configMapGenerator:
- name: amibot-config
  namespace: development
  options:
    labels:
      app: amibot
  files:
  - configs/amibot.conf
resources:
- deployment/kubernetes/namespace.yaml
- deployment/kubernetes/release.yaml
