configMapGenerator:
- name: amibot-config
  options:
    labels:
      app: amibot
  files:
  - configs/amibot_example.conf
resources:
- deployment/kubernetes/namespace.yaml
- deployment/kubernetes/release.yaml
