apiVersion: apps/v1
kind: Deployment
metadata:
  name: amibot
  namespace: development
  labels:
    app: amibot
    version: v0.0.5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amibot
  template:
    metadata:
      name: amibot
      labels:
        app: amibot
        mode: gateway
    spec:
      containers:
        - name: amibot
          image: registry.gitlab.com/donrudo/amibot:0.0.5
          imagePullPolicy: Always
          command: ['scripts/start.sh','configs/amibot.yaml']
          volumeMounts:
            - mountPath: /nonexistent/configs
              name: config-volume
          ports:
          - containerPort: 23459
          readinessProbe:
            httpGet:
              path: /readiness
              port: 23459
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /liveness
              port: 23459
            initialDelaySeconds: 5
            periodSeconds: 5
      dnsPolicy: "ClusterFirstWithHostNet"
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: amibot-config
